# Change these first
owner: cgntv # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Capen Tj.Makmur API
    url: https://denus-capen-api.client.cognitive.id/
  - name: Sewa Jas Jogja
    url: https://sewajasjogja.com/
  - name: Lava Tour Merapi Adventure
    url: https://lavatourmerapi-adv.online/
  # - name: Mocca Thrift.
    # url: https://mocca.gq/
  # - name: Universal Coconut
    # url: https://www.universalcoconut.net/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.cognitive.id
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Uptime monitor and status page for Cognitive services
  introMessage: This is a status page uses **real-time** data from our [GitHub repository](https://github.com/cgntv/upptime).
  navbar:
    - title: Home
      href: https://cognitive.id
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  scripts:
    - src: https://ackee.cognitive.id/ackee.js
  js: 'ackeeTracker.create("https://ackee.cognitive.id",{detailed:!0,ignoreLocalhost:!0,ignoreOwnVisits:!1}).record("296285c7-75c6-44ec-8df7-2504d59f512d");'

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
